In [1]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
import gspread
import time
import json
import pygsheets
from google.oauth2 import service_account
from oauth2client.service_account import ServiceAccountCredentials
from selenium.webdriver.common.by import By

scope = ["https://www.googleapis.com/auth/spreadsheets","https://www.googleapis.com/auth/drive.file","https://www.googleapis.com/auth/drive"]
with open("/Users/zachkarol/Movie_project/movie-project-330118-9bf05ce7085e.json") as source:
    info = json.load(source)
creds = service_account.Credentials.from_service_account_info(info)

# creds= ServiceAccountCredentials.from_json_keyfile_name("/Users/zachkarol/Movie_project/movie-project-330118-9bf05ce7085e.json", scope)
client=pygsheets.authorize(service_account_file="/Users/zachkarol/Movie_project/movie-project-330118-9bf05ce7085e.json")

In [4]:
sheet=client.open("Movie_proj").sheet1
df = pd.DataFrame(sheet.get_all_records())

In [5]:
##
df

,Movie,Rating(0 to 5)(need to find better system,Notes,Cumlative Moving Average,7 movieing average(haha laugh its fucking funny. The jokes is it is moving average but its a movieing average. Plz laugh),First actor,director,genre
0,Parasite,4.5,,4,,Cho Yeo-jeong,Bong Joon-ho,Thriller
1,A clockwork orange,5,,3.75,,Malcolm McDowell,Stanley Kubrick,Drama
2,The shining,2.5,,2.5,,Jack Nicholson,Stanley Kubrick,Horror
3,Dr strangelove,4,,3.25,,Peter Sellers,Stanley Kubrick,Comedy
4,The Rise of Skywalker,2,,2.83333,,Daisy Ridley,J.J. Abrams,Action
...,...,...,...,...,...,...,...,...
133,Arrival,4.5,,3.79198,3.6875,Amy Adams,Denis Villeneuve,Science fiction
134,No time to die,3,,,3.59375,Daniel Craig,Cary Joji Fukunaga,Action
135,Dune,4.5,,,3.59375,Timothée Chalamet,Denis Villeneuve,Action
136,Fast and furious,5,,,3.8125,Vin Diesel,,NA
137,Friday 13th 2009,2.75,,,,Jared Padalecki,Marcus Nispel,Horror